version: '3'

services:
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: bitnami/prometheus:2.45.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/opt/bitnami/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:9.5.6
    volumes:
      - ./config/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./config/grafana_config.ini:/etc/grafana/config.ini
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge